spring:
  jpa:
    hibernate:
      ddl-auto: update  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
  profiles:
    include: mariadb
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
  #            client-secret:
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: true